### ISSUE TITLE
Support for Python 3.10.7

### ISSUE THREAD

**Issue by lnagel** [hisdream86/drf-async-view#3]
I'm having trouble installing this package on Python 3.10.7 since the version does not meet package requirements (0.2.1 Requires-Python >=3.8,<=3.10)

I assume the problem is that 3.10.7 is not less or equal to 3.10.

Could you update your requirements from >=3.8,<=3.10 to >=3.8,<3.11 instead to resolve this?

**Comment by mikulas-mrva** [comment]
Getting the same issue trying to install your package in poetry.
```  
ERROR: Package 'drfasyncview' requires a different Python: 3.10.7 not in '<=3.10,>=3.8'
```

**Comment by mikulas-mrva** [comment]
Submitted a PR now, see #4

**Comment by hisdream86** [comment]
Thanks for your excellent advice, guys 👍 

[The fixed version](https://pypi.org/project/drfasyncview/0.2.2/) has been deployed for now.
